# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'NTT-Japan PaaS Developer(7)(6747898f-5136-4160-9d4c-848883672ac2)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload --account-name lmsstoragemain -f /home/vsts/work/_temp/azureclitaskscript1621318403039.ps1 -c test -n "2. S1.txt" --auth-mode login'
    
    
    
- task: AzureCLI@2
  inputs:
    azureSubscription: 'NTT-Japan PaaS Developer(7)(6747898f-5136-4160-9d4c-848883672ac2)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload --account-name lmsstoragemain -f /home/vsts/work/_temp/azureclitaskscript1621318396018.ps1 -c test -n "3. S2.txt" --auth-mode login'